CREATE TABLE [dbo].[FichaIndividual] (
    [NumFicha]                NCHAR (7)       NULL,
    [NumFichaLote1]           NCHAR (2)       NULL,
    [NumFichaLote2]           NCHAR (2)       NULL,
    [Cuc]                     NCHAR (12)      NOT NULL,
    [Chc]                     NCHAR (11)      NULL,
    [CRC_Ubigeo]              NCHAR (6)       NULL,
    [CRC_Sector]              NCHAR (2)       NULL,
    [CRC_Manzana]             NCHAR (3)       NULL,
    [CRC_Lote]                NCHAR (3)       NULL,
    [CRC_Edifica]             NCHAR (2)       NULL,
    [CRC_Entrada]             NCHAR (2)       NULL,
    [CRC_Piso]                NCHAR (2)       NULL,
    [CRC_Unidad]              NCHAR (3)       NULL,
    [CRC_DC]                  NCHAR (1)       NULL,
    [Ubi_NombreEdificacion]   NVARCHAR (MAX)  NULL,
    [Ubi_TipoEdificacion]     NVARCHAR (MAX)  NULL,
    [Ubi_TipoInterior]        NVARCHAR (MAX)  NULL,
    [Ubi_NumInterior]         NVARCHAR (50)   NULL,
    [Ubi_CodHU]               NVARCHAR (50)   NULL,
    [Ubi_NombreHU]            NVARCHAR (MAX)  NULL,
    [Ubi_ZonSecEta]           NVARCHAR (MAX)  NULL,
    [Ubi_Manzana]             NVARCHAR (MAX)  NULL,
    [Ubi_Lote]                NVARCHAR (MAX)  NULL,
    [Ubi_SubLote]             NVARCHAR (MAX)  NULL,
    [TipoTitular]             NCHAR (1)       NULL,
    [Tit1_EstadoCivil]        NCHAR (1)       NULL,
    [Tit1_TipoDoc]            NCHAR (1)       NULL,
    [Tit1_NumDoc]             NVARCHAR (10)   NULL,
    [Tit1_Nombres]            NVARCHAR (MAX)  NULL,
    [Tit1_ApellidoPaterno]    NVARCHAR (MAX)  NULL,
    [Tit1_ApellidoMaterno]    NVARCHAR (MAX)  NULL,
    [Tit2_TipoDoc]            NCHAR (1)       NULL,
    [Tit2_NumDoc]             NVARCHAR (10)   NULL,
    [Tit2_Nombres]            NVARCHAR (MAX)  NULL,
    [Tit2_ApellidoPaterno]    NVARCHAR (MAX)  NULL,
    [Tit2_ApellidoMaterno]    NVARCHAR (MAX)  NULL,
    [PersonaJuridica]         NCHAR (1)       NULL,
    [CondEspTit]              NCHAR (1)       NULL,
    [NumResExo]               NVARCHAR (50)   NULL,
    [NumBoletaPension]        NVARCHAR (50)   NULL,
    [InicioExo]               DATE            NULL,
    [FinExo]                  DATE            NULL,
    [Dpto]                    NVARCHAR (MAX)  NULL,
    [Prov]                    NVARCHAR (MAX)  NULL,
    [Dist]                    NVARCHAR (MAX)  NULL,
    [Telf]                    NVARCHAR (50)   NULL,
    [Anexo]                   NVARCHAR (50)   NULL,
    [Fax]                     NVARCHAR (50)   NULL,
    [CorreoElec]              NVARCHAR (50)   NULL,
    [CodVia]                  NCHAR (6)       NULL,
    [TipoVia]                 NVARCHAR (50)   NULL,
    [NombreVia]               NVARCHAR (MAX)  NULL,
    [NumMunicipal]            NVARCHAR (MAX)  NULL,
    [NombreEdificacion]       NVARCHAR (MAX)  NULL,
    [NumInterior]             NVARCHAR (MAX)  NULL,
    [CodHU]                   NVARCHAR (MAX)  NULL,
    [NombreHU]                NVARCHAR (MAX)  NULL,
    [ZonSecEta]               NVARCHAR (MAX)  NULL,
    [Manzana]                 NVARCHAR (MAX)  NULL,
    [Lote]                    NVARCHAR (MAX)  NULL,
    [SubLote]                 NVARCHAR (MAX)  NULL,
    [CondTit]                 NVARCHAR (MAX)  NULL,
    [CondTitEspec]            NVARCHAR (MAX)  NULL,
    [FormaAdquisicion]        NVARCHAR (MAX)  NULL,
    [FormaAdquisicionEspec]   NVARCHAR (MAX)  NULL,
    [FechaAdquisicion]        DATE            NULL,
    [CondEspPred]             NVARCHAR (MAX)  NULL,
    [NumResExoPred]           NVARCHAR (MAX)  NULL,
    [Porcentaje]              NUMERIC (18, 2) NULL,
    [FechaInicio]             DATE            NULL,
    [FechaVenc]               DATE            NULL,
    [DescripcionPredio]       NVARCHAR (MAX)  NULL,
    [DescripcionPredioEspec]  NVARCHAR (MAX)  NULL,
    [PredioEn]                NVARCHAR (MAX)  NULL,
    [PredioEnEspec]           NVARCHAR (MAX)  NULL,
    [CodUso]                  NCHAR (6)       NULL,
    [UsoPredioCatastral]      NVARCHAR (MAX)  NULL,
    [Estructuracion]          NVARCHAR (MAX)  NULL,
    [Zonificacion]            NVARCHAR (MAX)  NULL,
    [AreaTerrenoTitulo]       NUMERIC (18, 4) NULL,
    [AreaTerrenoDecladara]    NUMERIC (18, 4) NULL,
    [AreaTerrenoVerificada]   NUMERIC (18, 4) NULL,
    [Fr_Campo]                NUMERIC (18, 4) NULL,
    [Fr_Titulo]               NUMERIC (18, 4) NULL,
    [Fr_ColinCampo]           NUMERIC (18, 4) NULL,
    [Fr_ColinTit]             NUMERIC (18, 4) NULL,
    [De_Campo]                NUMERIC (18, 4) NULL,
    [De_Titulo]               NUMERIC (18, 4) NULL,
    [De_ColinCampo]           NUMERIC (18, 4) NULL,
    [De_ColinTit]             NUMERIC (18, 4) NULL,
    [Iz_Campo]                NUMERIC (18, 4) NULL,
    [Iz_Titulo]               NUMERIC (18, 4) NULL,
    [Iz_ColinCampo]           NUMERIC (18, 4) NULL,
    [Iz_ColinTit]             NUMERIC (18, 4) NULL,
    [Fo_Campo]                NUMERIC (18, 4) NULL,
    [Fo_Titulo]               NUMERIC (18, 4) NULL,
    [Fo_ColinCampo]           NUMERIC (18, 4) NULL,
    [Fo_ColinTit]             NUMERIC (18, 4) NULL,
    [Luz]                     BIT             NULL,
    [Agua]                    BIT             NULL,
    [Telefonia]               BIT             NULL,
    [Desague]                 BIT             NULL,
    [NumSuministroLuz]        NVARCHAR (MAX)  NULL,
    [NumContratoAgua]         NVARCHAR (MAX)  NULL,
    [NumTelf]                 NVARCHAR (MAX)  NULL,
    [PorcTerrLegal]           NUMERIC (18, 4) NULL,
    [PorTerrFisico]           NUMERIC (18, 4) NULL,
    [PorConsLegal]            NUMERIC (18, 4) NULL,
    [PorConsFisico]           NUMERIC (18, 4) NULL,
    [NombreNotaria]           NVARCHAR (MAX)  NULL,
    [Kardex]                  NVARCHAR (MAX)  NULL,
    [FechaEscrituraPub]       DATE            NULL,
    [PR_Num]                  NVARCHAR (MAX)  NULL,
    [PR_Fojas]                NVARCHAR (MAX)  NULL,
    [PR_Asiento]              NVARCHAR (MAX)  NULL,
    [PR_FechaInscripcion]     DATE            NULL,
    [PR_DeclaratoriaFabrica]  BIT             NULL,
    [PR_ASInsFab]             NVARCHAR (MAX)  NULL,
    [PR_FechaInsFab]          DATE            NULL,
    [Eval_Omiso]              BIT             NULL,
    [Eval_SubVal]             BIT             NULL,
    [Eval_SobreVal]           BIT             NULL,
    [Eval_Conf]               BIT             NULL,
    [Invadida_LoteColin]      NUMERIC (18, 4) NULL,
    [Invadida_AreaPub]        NUMERIC (18, 4) NULL,
    [Invadida_JardinAis]      NUMERIC (18, 4) NULL,
    [Invadida_AreaIntangible] NUMERIC (18, 4) NULL,
    [CondDeclarante]          NVARCHAR (50)   NULL,
    [CondDeclaranteEspec]     NVARCHAR (MAX)  NULL,
    [Lit1_TD]                 NCHAR (2)       NULL,
    [Lit1_NumDoc]             NVARCHAR (50)   NULL,
    [Lit1_NomApe]             NVARCHAR (MAX)  NULL,
    [Lit1_CodContr]           NVARCHAR (MAX)  NULL,
    [Lit2_TD]                 NCHAR (2)       NULL,
    [Lit2_NumDoc]             NVARCHAR (50)   NULL,
    [Lit2_NomApe]             NVARCHAR (MAX)  NULL,
    [Lit2_CodContr]           NVARCHAR (MAX)  NULL,
    [EstadoLlenadoFicha]      NCHAR (1)       NULL,
    [NumHabitantes]           NUMERIC (18)    NULL,
    [NumFamilias]             NUMERIC (18)    NULL,
    [Mantenimiento]           NCHAR (1)       NULL,
    [Observaciones]           NVARCHAR (MAX)  NULL,
    [DeclaranteDNI]           NVARCHAR (50)   NULL,
    [DeclaranteNombres]       NVARCHAR (MAX)  NULL,
    [DeclaranteApellidos]     NVARCHAR (MAX)  NULL,
    [DeclaranteFecha]         DATE            NULL,
    [DeclaranteFirma]         IMAGE           NULL,
    [SupervisorDNI]           NVARCHAR (50)   NULL,
    [SupervisorNombres]       NVARCHAR (MAX)  NULL,
    [SupervisorApellidos]     NVARCHAR (MAX)  NULL,
    [SupervisorFecha]         DATE            NULL,
    [SupervisorFirma]         IMAGE           NULL,
    [TecCatastralDNI]         NVARCHAR (50)   NULL,
    [TecCatastralNombres]     NVARCHAR (MAX)  NULL,
    [TecCatastralApellidos]   NVARCHAR (MAX)  NULL,
    [TecCatastralFecha]       DATE            NULL,
    [TecCatastralFirma]       IMAGE           NULL,
    [VerCatastralDNI]         NVARCHAR (50)   NULL,
    [VerCatastralNombres]     NVARCHAR (MAX)  NULL,
    [VerCatastralApellidos]   NVARCHAR (MAX)  NULL,
    [VerCatastralFecha]       DATE            NULL,
    [VerCatastralFirma]       IMAGE           NULL,
    [SelloTiempo] DATETIME NULL, 
    [UserName] NVARCHAR(MAX) NULL, 
    CONSTRAINT [PK_FichaIndividual] PRIMARY KEY CLUSTERED ([Cuc] ASC)
);

